// ── MODES ──────────────────────────────────────────────────────────────────

// xpMultiplier: fator aplicado ao score para calcular XP ganho por partida.
// Rush tem o menor multiplicador pois dura 5 min e gera scores altos com facilidade.
// Daily tem o maior pois são 20 perguntas fixas — exige consistência real.
export const MODES = {
  rush: {
    id: 'rush',
    name: 'Rush',
    emoji: '⚡',
    description: '5 minutos + bônus por acerto',
    gradient: 'from-violet-500 to-purple-600',
    gradientLight: 'from-violet-50 to-purple-50',
    shadow: 'shadow-violet-200',
    text: 'text-violet-600',
    border: 'border-violet-200',
    bg: 'bg-violet-600',
    timer: 300,
    lives: null,
    questions: null,
    bonusTime: 1,
    xpMultiplier: 0.12,
    scoreScale: 0.25,   // Rush dura 5 min → score bruto muito alto; escala para ~300 pontos médios
    group: 'main',
  },
  survival: {
    id: 'survival',
    name: 'Sobrevivência',
    emoji: '❤️',
    description: '3 vidas — sem limite de tempo',
    gradient: 'from-rose-500 to-pink-600',
    gradientLight: 'from-rose-50 to-pink-50',
    shadow: 'shadow-rose-200',
    text: 'text-rose-600',
    border: 'border-rose-200',
    bg: 'bg-rose-500',
    timer: null,
    lives: 3,
    questions: null,
    bonusTime: 0,
    xpMultiplier: 0.20,
    group: 'main',
  },
  speed: {
    id: 'speed',
    name: 'Velocidade',
    emoji: '⏱️',
    description: '60 segundos intensos',
    gradient: 'from-amber-400 to-orange-500',
    gradientLight: 'from-amber-50 to-orange-50',
    shadow: 'shadow-amber-200',
    text: 'text-amber-600',
    border: 'border-amber-200',
    bg: 'bg-amber-500',
    timer: 60,
    lives: null,
    questions: null,
    bonusTime: 0,
    xpMultiplier: 0.16,
    group: 'main',
  },
  daily: {
    id: 'daily',
    name: 'Desafio Diário',
    emoji: '🌟',
    description: '20 perguntas únicas por dia',
    gradient: 'from-emerald-400 to-teal-600',
    gradientLight: 'from-emerald-50 to-teal-50',
    shadow: 'shadow-emerald-200',
    text: 'text-emerald-600',
    border: 'border-emerald-200',
    bg: 'bg-emerald-500',
    timer: null,
    lives: null,
    questions: 20,
    bonusTime: 0,
    xpMultiplier: 0.28,
    group: 'main',
  },
  // ── MODOS DE TREINO — aprendizado sem pressão competitiva ─────────────────
  zen: {
    id: 'zen',
    name: 'Zen',
    emoji: '🧘',
    description: 'Treino livre, sem pressão',
    gradient: 'from-teal-400 to-cyan-500',
    gradientLight: 'from-teal-50 to-cyan-50',
    shadow: 'shadow-teal-200',
    text: 'text-teal-600',
    border: 'border-teal-200',
    bg: 'bg-teal-500',
    timer: null,
    lives: null,
    questions: null,
    bonusTime: 0,
    xpMultiplier: 0.10,   // baixo, mas existe (discreto — o jogador descobre)
    group: 'training',
  },
  review: {
    id: 'review',
    name: 'Revisão',
    emoji: '📚',
    description: 'Foca onde você mais erra',
    gradient: 'from-blue-500 to-indigo-600',
    gradientLight: 'from-blue-50 to-indigo-50',
    shadow: 'shadow-blue-200',
    text: 'text-blue-600',
    border: 'border-blue-200',
    bg: 'bg-blue-500',
    timer: null,
    lives: null,
    questions: 15,        // 15 questões focadas nas tabuadas mais erradas
    bonusTime: 0,
    xpMultiplier: 0.16,   // estudo focado — XP médio
    group: 'training',
  },
  // ── MODO DIFÍCIL — pool exclusivo de 7, 8 e 9 ──────────────────────────────
  hard: {
    id: 'hard',
    name: 'Difícil',
    emoji: '🔥',
    description: 'Só tabuadas 7, 8 e 9 · 90 segundos',
    gradient: 'from-orange-500 to-red-600',
    gradientLight: 'from-orange-50 to-red-50',
    shadow: 'shadow-orange-200',
    text: 'text-orange-600',
    border: 'border-orange-200',
    bg: 'bg-orange-500',
    timer: 90,
    lives: null,
    questions: null,
    bonusTime: 0,
    xpMultiplier: 0.22,   // maior que os modos padrão — recompensa pela dificuldade
    minLevel: 8,           // desbloqueado no Nível 8+
    group: 'advanced',
  },
  // ── MODO RECORDE PESSOAL — bater os próprios tempos por fato ──────────────
  personal: {
    id: 'personal',
    name: 'Recorde Pessoal',
    emoji: '⏱️',
    description: 'Bata seu próprio tempo em cada fato',
    gradient: 'from-yellow-500 to-amber-600',
    gradientLight: 'from-yellow-50 to-amber-50',
    shadow: 'shadow-yellow-200',
    text: 'text-yellow-600',
    border: 'border-yellow-200',
    bg: 'bg-yellow-500',
    timer: null,
    lives: null,
    questions: 15,
    bonusTime: 0,
    xpMultiplier: 0.18,
    personal: true,        // flag para o GamePage marcar "bateu tempo"
    group: 'advanced',
  },
  // ── DESAFIO SEMANAL — 10 questões iguais para todos por semana ────────────
  weekly: {
    id: 'weekly',
    name: 'Desafio Semanal',
    emoji: '🏆',
    description: 'Mesmas 10 questões — leaderboard global',
    gradient: 'from-pink-500 to-rose-600',
    gradientLight: 'from-pink-50 to-rose-50',
    shadow: 'shadow-pink-200',
    text: 'text-pink-600',
    border: 'border-pink-200',
    bg: 'bg-pink-500',
    timer: null,
    lives: null,
    questions: 10,
    bonusTime: 0,
    xpMultiplier: 0.30,   // alta recompensa — sai 1× por semana
    group: 'advanced',
  },
  // ── MODO COMBINADO — duas operações: "3 × 7 + 4 = ?" ───────────────────────
  combined: {
    id: 'combined',
    name: 'Combinado',
    emoji: '➕',
    description: 'Cálculo mental: a × b + c',
    gradient: 'from-violet-600 to-fuchsia-600',
    gradientLight: 'from-violet-50 to-fuchsia-50',
    shadow: 'shadow-violet-200',
    text: 'text-violet-700',
    border: 'border-violet-200',
    bg: 'bg-violet-600',
    timer: null,
    lives: null,
    questions: 15,
    bonusTime: 0,
    xpMultiplier: 0.25,
    minCertificates: 3,    // exige 3 certificados de domínio para desbloquear
    combined: true,
    group: 'advanced',
  },
  // ── MODO INVERSO — "= 56" → digite os dois fatores ─────────────────────────
  inverse: {
    id: 'inverse',
    name: 'Inverso',
    emoji: '🔄',
    description: '"= 56" → diga os dois fatores',
    gradient: 'from-indigo-500 to-blue-600',
    gradientLight: 'from-indigo-50 to-blue-50',
    shadow: 'shadow-indigo-200',
    text: 'text-indigo-600',
    border: 'border-indigo-200',
    bg: 'bg-indigo-500',
    timer: null,
    lives: null,
    questions: 15,        // 15 questões — modo de treino exigente
    bonusTime: 0,
    xpMultiplier: 0.20,   // recompensa moderada — modo desafiador
    inverse: true,        // flag para o GamePage usar duas entradas
    group: 'advanced',
  },
};

// Modos exibidos no grid principal do menu (os 4 clássicos)
export const MODE_LIST = Object.values(MODES).filter((m) => m.group === 'main');
// Modos de treino (Zen + Revisão)
export const TRAINING_MODE_LIST = Object.values(MODES).filter((m) => m.group === 'training');

// ── LEVELS ─────────────────────────────────────────────────────────────────
// Progressão de 28 níveis. Cada nível tem nome, título (identidade do usuário),
// emoji (também usado como avatar) e XP necessário.
//
// CURVA v3.0 — EQUILIBRADA (thresholds = original × 2, XP por modo variável):
//   Estimativa (2–3 partidas/dia, score ~150 pts, modo misto): ~60 XP/dia
//     Nível 2 em ~1 semana | Nível 5 em ~1 mês | Nível 10 em ~5 meses
//     Nível 15 em ~1.5 anos | Nível 20 em ~4 anos | Nível 28 = lendário
//   XP é baseado em desempenho (score × xpMultiplier do modo) — sem bônus de dia.
//   getLevelIdx() é baseado em XP acumulado (retrocompatível).

export const LEVELS = [
  { name: 'Iniciante',         title: 'Primeiros Passos',        xp: 0,       badge: '🌱' },
  { name: 'Aprendiz',          title: 'Aprendiz Curioso',        xp: 360,     badge: '📚' },
  { name: 'Estudante',         title: 'Estudante Dedicado',      xp: 800,     badge: '✏️' },
  { name: 'Calculador',        title: 'Calculador Iniciante',    xp: 1350,    badge: '🧮' },
  { name: 'Praticante',        title: 'Praticante Constante',    xp: 2000,    badge: '🎯' },
  { name: 'Ágil',              title: 'Mente Ágil',              xp: 2800,    badge: '⚡' },
  { name: 'Veloz',             title: 'Raciocínio Veloz',        xp: 4000,    badge: '🚀' },
  { name: 'Hábil',             title: 'Hábil nos Números',       xp: 5200,    badge: '🎲' },
  { name: 'Competente',        title: 'Competente Confiante',    xp: 6800,    badge: '💪' },
  { name: 'Avançado',          title: 'Pensador Avançado',       xp: 8800,    badge: '📐' },
  { name: 'Estrategista',      title: 'Estrategista Numérico',   xp: 11200,   badge: '♟️' },
  { name: 'Tático',            title: 'Tático da Tabuada',       xp: 14000,   badge: '🗺️' },
  { name: 'Perito',            title: 'Perito em Cálculo',       xp: 17800,   badge: '🔬' },
  { name: 'Especialista',      title: 'Especialista Matemático', xp: 22200,   badge: '🎓' },
  { name: 'Exímio',            title: 'Exímio Calculista',       xp: 27800,   badge: '✨' },
  { name: 'Virtuoso',          title: 'Virtuoso dos Números',    xp: 34800,   badge: '🎼' },
  { name: 'Mestre',            title: 'Mestre da Tabuada',       xp: 43400,   badge: '🏅' },
  { name: 'Grão-Mestre',       title: 'Grão-Mestre Numérico',    xp: 53800,   badge: '🥇' },
  { name: 'Sábio',             title: 'Sábio dos Cálculos',      xp: 67000,   badge: '📜' },
  { name: 'Erudito',           title: 'Erudito Matemático',      xp: 83000,   badge: '🦉' },
  { name: 'Prodígio',          title: 'Prodígio dos Números',    xp: 102800,  badge: '💫' },
  { name: 'Gênio',             title: 'Gênio em Ascensão',       xp: 127400,  badge: '🧩' },
  { name: 'Gênio Matemático',  title: 'Gênio Matemático',        xp: 157600,  badge: '🧠' },
  { name: 'Mente Brilhante',   title: 'Mente Brilhante',         xp: 195000,  badge: '💡' },
  { name: 'Lenda',             title: 'Lenda Viva',              xp: 241200,  badge: '👑' },
  { name: 'Lenda Numérica',    title: 'Lenda Numérica',          xp: 298400,  badge: '🔱' },
  { name: 'Mito',              title: 'Mito da Matemática',      xp: 368800,  badge: '🌟' },
  { name: 'Transcendente',     title: 'Calculadora Humana',      xp: 455800,  badge: '♾️' },
];

// Metas de ofensiva diária que o usuário pode escolher (modal de login / nova meta)
export const STREAK_GOALS = [5, 10, 15, 20, 35, 40];

// Marcos de ofensiva (dias consecutivos absolutos) que dão ESCOLHA DE RECOMPENSA.
// A partir de 40 dias e seguindo em 100, 250, 365. Após a virada de ano a ofensiva
// reinicia (as conquistas, não).
export const STREAK_REWARD_MILESTONES = [40, 100, 250, 365];

// ── ACHIEVEMENTS ───────────────────────────────────────────────────────────

export const ACHIEVEMENTS = [
  {
    id: 'first_game',
    title: 'Primeiro Passo',
    desc: 'Complete sua primeira partida',
    icon: '🎯',
    category: 'Progresso',
    check: (s) => s.totalGames >= 1,
  },
  {
    id: 'score_100',
    title: 'Centenário',
    desc: 'Faça 100 pontos em uma partida',
    icon: '💯',
    category: 'Pontuação',
    check: (s) => s.bestScore >= 100,
  },
  {
    id: 'score_300',
    title: 'Trezentos',
    desc: 'Faça 300 pontos em uma partida',
    icon: '🏅',
    category: 'Pontuação',
    check: (s) => s.bestScore >= 300,
  },
  {
    id: 'score_500',
    title: 'Quinhentos',
    desc: 'Faça 500 pontos em uma partida',
    icon: '🏆',
    category: 'Pontuação',
    check: (s) => s.bestScore >= 500,
  },
  {
    id: 'streak_5',
    title: 'Aquecendo',
    desc: '5 acertos consecutivos',
    icon: '🔥',
    category: 'Sequência',
    check: (s) => s.bestStreak >= 5,
  },
  {
    id: 'streak_10',
    title: 'Em Chamas',
    desc: '10 acertos consecutivos',
    icon: '🔥',
    category: 'Sequência',
    check: (s) => s.bestStreak >= 10,
  },
  {
    id: 'streak_20',
    title: 'Invencível',
    desc: '20 acertos consecutivos',
    icon: '⚡',
    category: 'Sequência',
    check: (s) => s.bestStreak >= 20,
  },
  {
    id: 'games_5',
    title: 'Comprometido',
    desc: 'Complete 5 partidas',
    icon: '🎮',
    category: 'Dedicação',
    check: (s) => s.totalGames >= 5,
  },
  {
    id: 'games_20',
    title: 'Veterano',
    desc: 'Complete 20 partidas',
    icon: '🌟',
    category: 'Dedicação',
    check: (s) => s.totalGames >= 20,
  },
  {
    id: 'games_50',
    title: 'Lendário',
    desc: 'Complete 50 partidas',
    icon: '👑',
    category: 'Dedicação',
    check: (s) => s.totalGames >= 50,
  },
  {
    id: 'accuracy_90',
    title: 'Precisão Cirúrgica',
    desc: '90%+ de acertos em uma partida com 10+ respostas',
    icon: '🎯',
    category: 'Precisão',
    check: (s) => s.bestAccuracy >= 90,
  },
  {
    id: 'daily_first',
    title: 'Desafiante',
    desc: 'Complete o Desafio Diário pela 1ª vez',
    icon: '🗓️',
    category: 'Diário',
    check: (s) => s.dailyCompleted >= 1,
  },
  {
    id: 'daily_7',
    title: 'Consistente',
    desc: 'Complete o Desafio Diário 7 vezes',
    icon: '📅',
    category: 'Diário',
    check: (s) => s.dailyCompleted >= 7,
  },
  {
    id: 'all_modes',
    title: 'Explorador',
    desc: 'Jogue todos os 4 modos de jogo',
    icon: '🗺️',
    category: 'Exploração',
    check: (s) => (s.modesPlayed || []).length >= 4,
  },
  {
    id: 'survival_30',
    title: 'Sobrevivente',
    desc: 'Responda 30 perguntas no modo Sobrevivência',
    icon: '💪',
    category: 'Modos',
    check: (s) => s.survivalBest >= 30,
  },
  {
    id: 'speed_20',
    title: 'Raio',
    desc: 'Responda 20 perguntas no modo Velocidade',
    icon: '⚡',
    category: 'Modos',
    check: (s) => s.speedBest >= 20,
  },

  // ── OFENSIVA (dias consecutivos jogando) ──────────────────────────────────
  {
    id: 'ofensiva_5',
    title: 'Faísca',
    desc: 'Mantenha 5 dias de ofensiva',
    icon: '🔥',
    category: 'Ofensiva',
    check: (s) => (s.bestDayStreak || 0) >= 5,
  },
  {
    id: 'ofensiva_10',
    title: 'Chama Acesa',
    desc: 'Mantenha 10 dias de ofensiva',
    icon: '🔥',
    category: 'Ofensiva',
    check: (s) => (s.bestDayStreak || 0) >= 10,
  },
  {
    id: 'ofensiva_15',
    title: 'Constância',
    desc: 'Mantenha 15 dias de ofensiva',
    icon: '🔥',
    category: 'Ofensiva',
    check: (s) => (s.bestDayStreak || 0) >= 15,
  },
  {
    id: 'ofensiva_20',
    title: 'Disciplina',
    desc: 'Mantenha 20 dias de ofensiva',
    icon: '🔥',
    category: 'Ofensiva',
    check: (s) => (s.bestDayStreak || 0) >= 20,
  },
  {
    id: 'ofensiva_35',
    title: 'Inabalável',
    desc: 'Mantenha 35 dias de ofensiva',
    icon: '🔥',
    category: 'Ofensiva',
    check: (s) => (s.bestDayStreak || 0) >= 35,
  },
  {
    id: 'ofensiva_40',
    title: 'Fogo Eterno',
    desc: 'Mantenha 40 dias de ofensiva',
    icon: '🔥',
    category: 'Ofensiva',
    check: (s) => (s.bestDayStreak || 0) >= 40,
  },
  {
    id: 'ofensiva_100',
    title: 'Centena em Chamas',
    desc: 'Mantenha 100 dias de ofensiva',
    icon: '💯',
    category: 'Ofensiva',
    check: (s) => (s.bestDayStreak || 0) >= 100,
  },
  {
    id: 'ofensiva_250',
    title: 'Inferno Imparável',
    desc: 'Mantenha 250 dias de ofensiva',
    icon: '🌋',
    category: 'Ofensiva',
    check: (s) => (s.bestDayStreak || 0) >= 250,
  },
  {
    id: 'ofensiva_365',
    title: 'Ano de Fogo',
    desc: 'Mantenha 365 dias de ofensiva',
    icon: '🎆',
    category: 'Ofensiva',
    check: (s) => (s.bestDayStreak || 0) >= 365,
  },
];
