// ── MODES ──────────────────────────────────────────────────────────────────

export const MODES = {
  rush: {
    id: 'rush',
    name: 'Rush',
    emoji: '⚡',
    description: '5 minutos + bônus por acerto',
    gradient: 'from-violet-500 to-purple-600',
    gradientLight: 'from-violet-50 to-purple-50',
    shadow: 'shadow-violet-200',
    text: 'text-violet-600',
    border: 'border-violet-200',
    bg: 'bg-violet-600',
    timer: 300,
    lives: null,
    questions: null,
    bonusTime: 1,
  },
  survival: {
    id: 'survival',
    name: 'Sobrevivência',
    emoji: '❤️',
    description: '3 vidas — sem limite de tempo',
    gradient: 'from-rose-500 to-pink-600',
    gradientLight: 'from-rose-50 to-pink-50',
    shadow: 'shadow-rose-200',
    text: 'text-rose-600',
    border: 'border-rose-200',
    bg: 'bg-rose-500',
    timer: null,
    lives: 3,
    questions: null,
    bonusTime: 0,
  },
  speed: {
    id: 'speed',
    name: 'Velocidade',
    emoji: '⏱️',
    description: '60 segundos intensos',
    gradient: 'from-amber-400 to-orange-500',
    gradientLight: 'from-amber-50 to-orange-50',
    shadow: 'shadow-amber-200',
    text: 'text-amber-600',
    border: 'border-amber-200',
    bg: 'bg-amber-500',
    timer: 60,
    lives: null,
    questions: null,
    bonusTime: 0,
  },
  daily: {
    id: 'daily',
    name: 'Desafio Diário',
    emoji: '🌟',
    description: '20 perguntas únicas por dia',
    gradient: 'from-emerald-400 to-teal-600',
    gradientLight: 'from-emerald-50 to-teal-50',
    shadow: 'shadow-emerald-200',
    text: 'text-emerald-600',
    border: 'border-emerald-200',
    bg: 'bg-emerald-500',
    timer: null,
    lives: null,
    questions: 20,
    bonusTime: 0,
  },
};

export const MODE_LIST = Object.values(MODES);

// ── LEVELS ─────────────────────────────────────────────────────────────────

export const LEVELS = [
  { name: 'Iniciante',   xp: 0,    badge: '🌱' },
  { name: 'Aprendiz',    xp: 100,  badge: '📚' },
  { name: 'Calculador',  xp: 300,  badge: '🧮' },
  { name: 'Ágil',        xp: 600,  badge: '⚡' },
  { name: 'Expert',      xp: 1000, badge: '🎯' },
  { name: 'Mestre',      xp: 1500, badge: '🏆' },
  { name: 'Lenda',       xp: 2500, badge: '👑' },
];

// ── ACHIEVEMENTS ───────────────────────────────────────────────────────────

export const ACHIEVEMENTS = [
  {
    id: 'first_game',
    title: 'Primeiro Passo',
    desc: 'Complete sua primeira partida',
    icon: '🎯',
    category: 'Progresso',
    check: (s) => s.totalGames >= 1,
  },
  {
    id: 'score_100',
    title: 'Centenário',
    desc: 'Faça 100 pontos em uma partida',
    icon: '💯',
    category: 'Pontuação',
    check: (s) => s.bestScore >= 100,
  },
  {
    id: 'score_300',
    title: 'Trezentos',
    desc: 'Faça 300 pontos em uma partida',
    icon: '🏅',
    category: 'Pontuação',
    check: (s) => s.bestScore >= 300,
  },
  {
    id: 'score_500',
    title: 'Quinhentos',
    desc: 'Faça 500 pontos em uma partida',
    icon: '🏆',
    category: 'Pontuação',
    check: (s) => s.bestScore >= 500,
  },
  {
    id: 'streak_5',
    title: 'Aquecendo',
    desc: '5 acertos consecutivos',
    icon: '🔥',
    category: 'Sequência',
    check: (s) => s.bestStreak >= 5,
  },
  {
    id: 'streak_10',
    title: 'Em Chamas',
    desc: '10 acertos consecutivos',
    icon: '🔥',
    category: 'Sequência',
    check: (s) => s.bestStreak >= 10,
  },
  {
    id: 'streak_20',
    title: 'Invencível',
    desc: '20 acertos consecutivos',
    icon: '⚡',
    category: 'Sequência',
    check: (s) => s.bestStreak >= 20,
  },
  {
    id: 'games_5',
    title: 'Comprometido',
    desc: 'Complete 5 partidas',
    icon: '🎮',
    category: 'Dedicação',
    check: (s) => s.totalGames >= 5,
  },
  {
    id: 'games_20',
    title: 'Veterano',
    desc: 'Complete 20 partidas',
    icon: '🌟',
    category: 'Dedicação',
    check: (s) => s.totalGames >= 20,
  },
  {
    id: 'games_50',
    title: 'Lendário',
    desc: 'Complete 50 partidas',
    icon: '👑',
    category: 'Dedicação',
    check: (s) => s.totalGames >= 50,
  },
  {
    id: 'accuracy_90',
    title: 'Precisão Cirúrgica',
    desc: '90%+ de acertos em uma partida com 10+ respostas',
    icon: '🎯',
    category: 'Precisão',
    check: (s) => s.bestAccuracy >= 90,
  },
  {
    id: 'daily_first',
    title: 'Desafiante',
    desc: 'Complete o Desafio Diário pela 1ª vez',
    icon: '🗓️',
    category: 'Diário',
    check: (s) => s.dailyCompleted >= 1,
  },
  {
    id: 'daily_7',
    title: 'Consistente',
    desc: 'Complete o Desafio Diário 7 vezes',
    icon: '📅',
    category: 'Diário',
    check: (s) => s.dailyCompleted >= 7,
  },
  {
    id: 'all_modes',
    title: 'Explorador',
    desc: 'Jogue todos os 4 modos de jogo',
    icon: '🗺️',
    category: 'Exploração',
    check: (s) => (s.modesPlayed || []).length >= 4,
  },
  {
    id: 'survival_30',
    title: 'Sobrevivente',
    desc: 'Responda 30 perguntas no modo Sobrevivência',
    icon: '💪',
    category: 'Modos',
    check: (s) => s.survivalBest >= 30,
  },
  {
    id: 'speed_20',
    title: 'Raio',
    desc: 'Responda 20 perguntas no modo Velocidade',
    icon: '⚡',
    category: 'Modos',
    check: (s) => s.speedBest >= 20,
  },
];
