// ── MODES ──────────────────────────────────────────────────────────────────

export const MODES = {
  rush: {
    id: 'rush',
    name: 'Rush',
    emoji: '⚡',
    description: '5 minutos + bônus por acerto',
    gradient: 'from-violet-500 to-purple-600',
    gradientLight: 'from-violet-50 to-purple-50',
    shadow: 'shadow-violet-200',
    text: 'text-violet-600',
    border: 'border-violet-200',
    bg: 'bg-violet-600',
    timer: 300,
    lives: null,
    questions: null,
    bonusTime: 1,
  },
  survival: {
    id: 'survival',
    name: 'Sobrevivência',
    emoji: '❤️',
    description: '3 vidas — sem limite de tempo',
    gradient: 'from-rose-500 to-pink-600',
    gradientLight: 'from-rose-50 to-pink-50',
    shadow: 'shadow-rose-200',
    text: 'text-rose-600',
    border: 'border-rose-200',
    bg: 'bg-rose-500',
    timer: null,
    lives: 3,
    questions: null,
    bonusTime: 0,
  },
  speed: {
    id: 'speed',
    name: 'Velocidade',
    emoji: '⏱️',
    description: '60 segundos intensos',
    gradient: 'from-amber-400 to-orange-500',
    gradientLight: 'from-amber-50 to-orange-50',
    shadow: 'shadow-amber-200',
    text: 'text-amber-600',
    border: 'border-amber-200',
    bg: 'bg-amber-500',
    timer: 60,
    lives: null,
    questions: null,
    bonusTime: 0,
  },
  daily: {
    id: 'daily',
    name: 'Desafio Diário',
    emoji: '🌟',
    description: '20 perguntas únicas por dia',
    gradient: 'from-emerald-400 to-teal-600',
    gradientLight: 'from-emerald-50 to-teal-50',
    shadow: 'shadow-emerald-200',
    text: 'text-emerald-600',
    border: 'border-emerald-200',
    bg: 'bg-emerald-500',
    timer: null,
    lives: null,
    questions: 20,
    bonusTime: 0,
  },
};

export const MODE_LIST = Object.values(MODES);

// ── LEVELS ─────────────────────────────────────────────────────────────────
// Progressão de 28 níveis. Cada nível tem nome, título (identidade do usuário),
// emoji (também usado como avatar) e XP necessário. A curva é gradual no início
// (recompensa rápida) e cada vez mais íngreme (progressão de longo prazo).
// getLevelIdx() é puramente baseado em XP, então a expansão é retrocompatível.

export const LEVELS = [
  { name: 'Iniciante',         title: 'Primeiros Passos',        xp: 0,     badge: '🌱' },
  { name: 'Aprendiz',          title: 'Aprendiz Curioso',        xp: 100,   badge: '📚' },
  { name: 'Estudante',         title: 'Estudante Dedicado',      xp: 250,   badge: '✏️' },
  { name: 'Calculador',        title: 'Calculador Iniciante',    xp: 450,   badge: '🧮' },
  { name: 'Praticante',        title: 'Praticante Constante',    xp: 700,   badge: '🎯' },
  { name: 'Ágil',              title: 'Mente Ágil',              xp: 1000,  badge: '⚡' },
  { name: 'Veloz',             title: 'Raciocínio Veloz',        xp: 1400,  badge: '🚀' },
  { name: 'Hábil',             title: 'Hábil nos Números',       xp: 1900,  badge: '🎲' },
  { name: 'Competente',        title: 'Competente Confiante',    xp: 2500,  badge: '💪' },
  { name: 'Avançado',          title: 'Pensador Avançado',       xp: 3200,  badge: '📐' },
  { name: 'Estrategista',      title: 'Estrategista Numérico',   xp: 4000,  badge: '♟️' },
  { name: 'Tático',            title: 'Tático da Tabuada',       xp: 5000,  badge: '🗺️' },
  { name: 'Perito',            title: 'Perito em Cálculo',       xp: 6200,  badge: '🔬' },
  { name: 'Especialista',      title: 'Especialista Matemático', xp: 7600,  badge: '🎓' },
  { name: 'Exímio',            title: 'Exímio Calculista',       xp: 9200,  badge: '✨' },
  { name: 'Virtuoso',          title: 'Virtuoso dos Números',    xp: 11000, badge: '🎼' },
  { name: 'Mestre',            title: 'Mestre da Tabuada',       xp: 13000, badge: '🏅' },
  { name: 'Grão-Mestre',       title: 'Grão-Mestre Numérico',    xp: 15500, badge: '🥇' },
  { name: 'Sábio',             title: 'Sábio dos Cálculos',      xp: 18500, badge: '📜' },
  { name: 'Erudito',           title: 'Erudito Matemático',      xp: 22000, badge: '🦉' },
  { name: 'Prodígio',          title: 'Prodígio dos Números',    xp: 26000, badge: '💫' },
  { name: 'Gênio',             title: 'Gênio em Ascensão',       xp: 31000, badge: '🧩' },
  { name: 'Gênio Matemático',  title: 'Gênio Matemático',        xp: 37000, badge: '🧠' },
  { name: 'Mente Brilhante',   title: 'Mente Brilhante',         xp: 44000, badge: '💡' },
  { name: 'Lenda',             title: 'Lenda Viva',              xp: 52000, badge: '👑' },
  { name: 'Lenda Numérica',    title: 'Lenda Numérica',          xp: 62000, badge: '🔱' },
  { name: 'Mito',              title: 'Mito da Matemática',      xp: 75000, badge: '🌟' },
  { name: 'Transcendente',     title: 'Calculadora Humana',      xp: 90000, badge: '♾️' },
];

// Metas de ofensiva diária disponíveis para o usuário escolher
export const STREAK_GOALS = [7, 15, 30, 100];

// ── ACHIEVEMENTS ───────────────────────────────────────────────────────────

export const ACHIEVEMENTS = [
  {
    id: 'first_game',
    title: 'Primeiro Passo',
    desc: 'Complete sua primeira partida',
    icon: '🎯',
    category: 'Progresso',
    check: (s) => s.totalGames >= 1,
  },
  {
    id: 'score_100',
    title: 'Centenário',
    desc: 'Faça 100 pontos em uma partida',
    icon: '💯',
    category: 'Pontuação',
    check: (s) => s.bestScore >= 100,
  },
  {
    id: 'score_300',
    title: 'Trezentos',
    desc: 'Faça 300 pontos em uma partida',
    icon: '🏅',
    category: 'Pontuação',
    check: (s) => s.bestScore >= 300,
  },
  {
    id: 'score_500',
    title: 'Quinhentos',
    desc: 'Faça 500 pontos em uma partida',
    icon: '🏆',
    category: 'Pontuação',
    check: (s) => s.bestScore >= 500,
  },
  {
    id: 'streak_5',
    title: 'Aquecendo',
    desc: '5 acertos consecutivos',
    icon: '🔥',
    category: 'Sequência',
    check: (s) => s.bestStreak >= 5,
  },
  {
    id: 'streak_10',
    title: 'Em Chamas',
    desc: '10 acertos consecutivos',
    icon: '🔥',
    category: 'Sequência',
    check: (s) => s.bestStreak >= 10,
  },
  {
    id: 'streak_20',
    title: 'Invencível',
    desc: '20 acertos consecutivos',
    icon: '⚡',
    category: 'Sequência',
    check: (s) => s.bestStreak >= 20,
  },
  {
    id: 'games_5',
    title: 'Comprometido',
    desc: 'Complete 5 partidas',
    icon: '🎮',
    category: 'Dedicação',
    check: (s) => s.totalGames >= 5,
  },
  {
    id: 'games_20',
    title: 'Veterano',
    desc: 'Complete 20 partidas',
    icon: '🌟',
    category: 'Dedicação',
    check: (s) => s.totalGames >= 20,
  },
  {
    id: 'games_50',
    title: 'Lendário',
    desc: 'Complete 50 partidas',
    icon: '👑',
    category: 'Dedicação',
    check: (s) => s.totalGames >= 50,
  },
  {
    id: 'accuracy_90',
    title: 'Precisão Cirúrgica',
    desc: '90%+ de acertos em uma partida com 10+ respostas',
    icon: '🎯',
    category: 'Precisão',
    check: (s) => s.bestAccuracy >= 90,
  },
  {
    id: 'daily_first',
    title: 'Desafiante',
    desc: 'Complete o Desafio Diário pela 1ª vez',
    icon: '🗓️',
    category: 'Diário',
    check: (s) => s.dailyCompleted >= 1,
  },
  {
    id: 'daily_7',
    title: 'Consistente',
    desc: 'Complete o Desafio Diário 7 vezes',
    icon: '📅',
    category: 'Diário',
    check: (s) => s.dailyCompleted >= 7,
  },
  {
    id: 'all_modes',
    title: 'Explorador',
    desc: 'Jogue todos os 4 modos de jogo',
    icon: '🗺️',
    category: 'Exploração',
    check: (s) => (s.modesPlayed || []).length >= 4,
  },
  {
    id: 'survival_30',
    title: 'Sobrevivente',
    desc: 'Responda 30 perguntas no modo Sobrevivência',
    icon: '💪',
    category: 'Modos',
    check: (s) => s.survivalBest >= 30,
  },
  {
    id: 'speed_20',
    title: 'Raio',
    desc: 'Responda 20 perguntas no modo Velocidade',
    icon: '⚡',
    category: 'Modos',
    check: (s) => s.speedBest >= 20,
  },
];
