// ── POOL DE MISSÕES DIÁRIAS ───────────────────────────────────────────────────
// 3 são sorteadas deterministicamente por dia
export const DAILY_MISSION_POOL = [
  {
    id: 'dm_play_1',
    title: 'Primeira Partida',
    desc: 'Jogue 1 partida hoje',
    type: 'play',
    target: 1,
    reward: 20,
    emoji: '🎮',
  },
  {
    id: 'dm_play_3',
    title: 'Três Partidas',
    desc: 'Jogue 3 partidas hoje',
    type: 'play',
    target: 3,
    reward: 40,
    emoji: '🎮',
  },
  {
    id: 'dm_daily',
    title: 'Desafio do Dia',
    desc: 'Complete o Desafio Diário',
    type: 'daily',
    target: 1,
    reward: 50,
    emoji: '🌟',
  },
  {
    id: 'dm_correct_20',
    title: '20 Acertos',
    desc: 'Acerte 20 contas em uma única partida',
    type: 'correct_single',
    target: 20,
    reward: 30,
    emoji: '✅',
  },
  {
    id: 'dm_correct_50',
    title: '50 Acertos',
    desc: 'Acerte 50 contas no total hoje',
    type: 'correct_day',
    target: 50,
    reward: 35,
    emoji: '✅',
  },
  {
    id: 'dm_streak_10',
    title: 'Sequência de 10',
    desc: 'Faça uma sequência de 10 acertos',
    type: 'streak',
    target: 10,
    reward: 40,
    emoji: '🔥',
  },
  {
    id: 'dm_streak_15',
    title: 'Sequência de 15',
    desc: 'Faça uma sequência de 15 acertos',
    type: 'streak',
    target: 15,
    reward: 55,
    emoji: '🔥',
  },
  {
    id: 'dm_acc_80',
    title: 'Precisão de 80%',
    desc: 'Alcance 80% de precisão em uma partida',
    type: 'accuracy',
    target: 80,
    reward: 45,
    emoji: '🎯',
  },
  {
    id: 'dm_acc_90',
    title: 'Precisão de 90%',
    desc: 'Alcance 90% de precisão em uma partida',
    type: 'accuracy',
    target: 90,
    reward: 60,
    emoji: '🎯',
  },
  {
    id: 'dm_score_100',
    title: 'Cem Pontos',
    desc: 'Faça 100 pontos em uma partida',
    type: 'score',
    target: 100,
    reward: 30,
    emoji: '💯',
  },
  {
    id: 'dm_score_200',
    title: 'Duzentos Pontos',
    desc: 'Faça 200 pontos em uma partida',
    type: 'score',
    target: 200,
    reward: 50,
    emoji: '💯',
  },
];

// ── POOL DE MISSÕES SEMANAIS ──────────────────────────────────────────────────
// 2 são sorteadas na segunda-feira. Metas exigem dedicação real de 5–7 dias.
export const WEEKLY_MISSION_POOL = [
  {
    id: 'wm_play_35',
    title: '35 Partidas',
    desc: 'Jogue 35 partidas esta semana (~5/dia)',
    type: 'play',
    target: 35,
    reward: 300,
    emoji: '🎮',
  },
  {
    id: 'wm_play_60',
    title: '60 Partidas',
    desc: 'Jogue 60 partidas esta semana (~9/dia)',
    type: 'play',
    target: 60,
    reward: 500,
    emoji: '🎮',
  },
  {
    id: 'wm_daily_7',
    title: 'Semana Perfeita',
    desc: 'Complete o Desafio Diário todos os 7 dias desta semana',
    type: 'daily',
    target: 7,
    reward: 600,
    emoji: '🌟',
  },
  {
    id: 'wm_correct_1000',
    title: 'Mil Acertos',
    desc: 'Acerte 1000 contas esta semana',
    type: 'correct_week',
    target: 1000,
    reward: 420,
    emoji: '✅',
  },
  {
    id: 'wm_correct_2000',
    title: 'Dois Mil Acertos',
    desc: 'Acerte 2000 contas esta semana',
    type: 'correct_week',
    target: 2000,
    reward: 750,
    emoji: '✅',
  },
  {
    id: 'wm_streak_20',
    title: 'Sequência de 20',
    desc: 'Faça uma sequência de 20 acertos em uma única partida',
    type: 'streak',
    target: 20,
    reward: 400,
    emoji: '🔥',
  },
  {
    id: 'wm_score_800',
    title: '800 Pontos',
    desc: 'Faça 800 pontos em uma única partida',
    type: 'score',
    target: 800,
    reward: 450,
    emoji: '💯',
  },
  {
    id: 'wm_acc_95',
    title: 'Precisão de 95%',
    desc: 'Termine uma partida com 95% ou mais de precisão',
    type: 'accuracy',
    target: 95,
    reward: 500,
    emoji: '🎯',
  },
];

// ── POOL DE MISSÕES MENSAIS ───────────────────────────────────────────────────
// 2 são sorteadas no primeiro dia do mês. Metas exigem um mês de dedicação real.
export const MONTHLY_MISSION_POOL = [
  {
    id: 'mm_play_120',
    title: '120 Partidas',
    desc: 'Jogue 120 partidas este mês (~4/dia)',
    type: 'play',
    target: 120,
    reward: 900,
    emoji: '🎮',
  },
  {
    id: 'mm_play_250',
    title: '250 Partidas',
    desc: 'Jogue 250 partidas este mês (~8/dia)',
    type: 'play',
    target: 250,
    reward: 1800,
    emoji: '🎮',
  },
  {
    id: 'mm_correct_4000',
    title: '4000 Acertos',
    desc: 'Acerte 4000 contas este mês (~130/dia)',
    type: 'correct_month',
    target: 4000,
    reward: 1000,
    emoji: '✅',
  },
  {
    id: 'mm_correct_8000',
    title: '8000 Acertos',
    desc: 'Acerte 8000 contas este mês (~270/dia)',
    type: 'correct_month',
    target: 8000,
    reward: 2200,
    emoji: '✅',
  },
  {
    id: 'mm_streak_month_25',
    title: '25 Dias de Ofensiva',
    desc: 'Mantenha 25 dias consecutivos de ofensiva este mês',
    type: 'streak_month',
    target: 25,
    reward: 800,
    emoji: '🔥',
  },
  {
    id: 'mm_daily_22',
    title: '22 Desafios Diários',
    desc: 'Complete o Desafio Diário 22 vezes este mês',
    type: 'daily',
    target: 22,
    reward: 1500,
    emoji: '🌟',
  },
  {
    id: 'mm_score_1200',
    title: 'Pontuação 1200',
    desc: 'Faça 1200 pontos em uma única partida',
    type: 'score',
    target: 1200,
    reward: 1100,
    emoji: '💯',
  },
];
