// ── POOL DE MISSÕES DIÁRIAS ───────────────────────────────────────────────────
// 3 são sorteadas deterministicamente por dia
export const DAILY_MISSION_POOL = [
  {
    id: 'dm_play_1',
    title: 'Primeira Partida',
    desc: 'Jogue 1 partida hoje',
    type: 'play',
    target: 1,
    reward: 20,
    emoji: '🎮',
  },
  {
    id: 'dm_play_3',
    title: 'Três Partidas',
    desc: 'Jogue 3 partidas hoje',
    type: 'play',
    target: 3,
    reward: 40,
    emoji: '🎮',
  },
  {
    id: 'dm_daily',
    title: 'Desafio do Dia',
    desc: 'Complete o Desafio Diário',
    type: 'daily',
    target: 1,
    reward: 50,
    emoji: '🌟',
  },
  {
    id: 'dm_correct_20',
    title: '20 Acertos',
    desc: 'Acerte 20 contas em uma única partida',
    type: 'correct_single',
    target: 20,
    reward: 30,
    emoji: '✅',
  },
  {
    id: 'dm_correct_50',
    title: '50 Acertos',
    desc: 'Acerte 50 contas no total hoje',
    type: 'correct_day',
    target: 50,
    reward: 35,
    emoji: '✅',
  },
  {
    id: 'dm_streak_10',
    title: 'Sequência de 10',
    desc: 'Faça uma sequência de 10 acertos',
    type: 'streak',
    target: 10,
    reward: 40,
    emoji: '🔥',
  },
  {
    id: 'dm_streak_15',
    title: 'Sequência de 15',
    desc: 'Faça uma sequência de 15 acertos',
    type: 'streak',
    target: 15,
    reward: 55,
    emoji: '🔥',
  },
  {
    id: 'dm_acc_80',
    title: 'Precisão de 80%',
    desc: 'Alcance 80% de precisão em uma partida',
    type: 'accuracy',
    target: 80,
    reward: 45,
    emoji: '🎯',
  },
  {
    id: 'dm_acc_90',
    title: 'Precisão de 90%',
    desc: 'Alcance 90% de precisão em uma partida',
    type: 'accuracy',
    target: 90,
    reward: 60,
    emoji: '🎯',
  },
  {
    id: 'dm_score_100',
    title: 'Cem Pontos',
    desc: 'Faça 100 pontos em uma partida',
    type: 'score',
    target: 100,
    reward: 30,
    emoji: '💯',
  },
  {
    id: 'dm_score_200',
    title: 'Duzentos Pontos',
    desc: 'Faça 200 pontos em uma partida',
    type: 'score',
    target: 200,
    reward: 50,
    emoji: '💯',
  },
];

// ── POOL DE MISSÕES SEMANAIS ──────────────────────────────────────────────────
// 2 são sorteadas na segunda-feira
export const WEEKLY_MISSION_POOL = [
  {
    id: 'wm_play_10',
    title: '10 Partidas',
    desc: 'Jogue 10 partidas esta semana',
    type: 'play',
    target: 10,
    reward: 150,
    emoji: '🎮',
  },
  {
    id: 'wm_play_20',
    title: '20 Partidas',
    desc: 'Jogue 20 partidas esta semana',
    type: 'play',
    target: 20,
    reward: 250,
    emoji: '🎮',
  },
  {
    id: 'wm_daily_5',
    title: '5 Desafios Diários',
    desc: 'Complete 5 Desafios Diários esta semana',
    type: 'daily',
    target: 5,
    reward: 300,
    emoji: '🌟',
  },
  {
    id: 'wm_correct_300',
    title: '300 Acertos',
    desc: 'Acerte 300 contas esta semana',
    type: 'correct_week',
    target: 300,
    reward: 200,
    emoji: '✅',
  },
  {
    id: 'wm_correct_500',
    title: '500 Acertos',
    desc: 'Acerte 500 contas esta semana',
    type: 'correct_week',
    target: 500,
    reward: 320,
    emoji: '✅',
  },
  {
    id: 'wm_streak_15',
    title: 'Sequência de 15',
    desc: 'Faça uma sequência de 15 acertos',
    type: 'streak',
    target: 15,
    reward: 200,
    emoji: '🔥',
  },
  {
    id: 'wm_score_500',
    title: '500 Pontos',
    desc: 'Faça 500 pontos em uma única partida',
    type: 'score',
    target: 500,
    reward: 250,
    emoji: '💯',
  },
];

// ── POOL DE MISSÕES MENSAIS ───────────────────────────────────────────────────
// 2 são sorteadas no primeiro dia do mês
export const MONTHLY_MISSION_POOL = [
  {
    id: 'mm_play_30',
    title: '30 Partidas',
    desc: 'Jogue 30 partidas este mês',
    type: 'play',
    target: 30,
    reward: 500,
    emoji: '🎮',
  },
  {
    id: 'mm_correct_1000',
    title: 'Mil Acertos',
    desc: 'Acerte 1000 contas este mês',
    type: 'correct_month',
    target: 1000,
    reward: 600,
    emoji: '✅',
  },
  {
    id: 'mm_streak_15',
    title: '15 Dias de Ofensiva',
    desc: 'Mantenha 15 dias de ofensiva este mês',
    type: 'streak_month',
    target: 15,
    reward: 400,
    emoji: '🔥',
  },
  {
    id: 'mm_daily_15',
    title: '15 Desafios Diários',
    desc: 'Complete 15 Desafios Diários este mês',
    type: 'daily',
    target: 15,
    reward: 700,
    emoji: '🌟',
  },
  {
    id: 'mm_play_50',
    title: '50 Partidas',
    desc: 'Jogue 50 partidas este mês',
    type: 'play',
    target: 50,
    reward: 800,
    emoji: '🎮',
  },
];
